version: '3'
services:
  web:
    image: nginx:alpine
#    links:
#      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    restart: always
    networks:
      - frontend 
    logging:
        driver: json-file
        options:
          max-size: 50m
  php:
    build: php-fpm-custom
    environment:
      - TYPO3_CONTEXT=Development/Docker
#    links:
#      - db
    #  - redis
    volumes:
      - ./htdocs:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - frontend
      - backend
    restart: always
    logging:
        driver: json-file
        options:
            max-size: 50m    
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=toiyeuvietnam1412
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    restart: always    
    logging:
        driver: json-file
        options:
            max-size: 50m
  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
#    links:
#        - db:db
    ports:
        - 6996:80
    networks:
        - backend
    logging:
        driver: json-file
        options:
            max-size: 50m
networks:
    frontend
    backend
        
